# config/packages/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: mail  # Використовуємо mail як унікальний ідентифікатор

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 тиждень
                path: /
                always_remember_me: false

    access_control:
        # Публічний доступ до логіну та реєстрації
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/user/blog, roles: ROLE_USER }
        - { path: ^/admin/blog, roles: ROLE_ADMIN }
        # Особистий кабінет потребує ролі користувача
        - { path: ^/user, roles: ROLE_USER }
        
        # Адмін-панель потребує ролі адміна
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # За замовчуванням - публічний доступ
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }