app_reset_password_request:
    path: /reset-password
    controller: App\Controller\Auth\ResetPasswordController::request
    methods: [GET, POST]

app_reset_password_reset:
    path: /reset-password/reset/{token}
    controller: App\Controller\Auth\ResetPasswordController::reset
    methods: [GET, POST]